In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('final_softcone_streamers.csv')

df['별풍선 도네이션'] = np.nan   
df['치즈 도네이션'] = np.nan
df['외부 인기지표'] = np.nan        

df.to_csv('final_softcone_streamers_V2.csv', index=False, encoding='utf-8-sig')

In [4]:
import pandas as pd
import numpy as np

# 1. 파일 불러오기
df = pd.read_csv('final_softcone_streamers_V2.csv')

# 1. 기준을 '별풍선 도네이션'에서 '치즈 도네이션'으로 바꿉니다!
target_index = df.columns.get_loc('치즈 도네이션') + 1

# 2. 넣을 이름을 '시간당 별풍선'에서 '시간당 치즈'로 바꿉니다!
df.insert(target_index, '시간당 치즈', np.nan)

# 4. 자리에 예쁘게 잘 들어갔는지 컬럼 이름들만 쫙 뽑아서 확인해볼까요?
print(df.columns)

# 5. 완벽하게 들어갔다면 V3로 새롭게 저장 꾹!
df.to_csv('final_softcone_streamers_V2.csv', index=False, encoding='utf-8-sig')

Index(['streamer_name', 'platform', 'channel_id', '날짜', '팔로워', '방송시간',
       '6분 최고채팅', '6분 평균 채팅수', '최고 시청자', '평균 시청자', '뷰어십', '별풍선 도네이션',
       '시간당 별풍선', '치즈 도네이션', '시간당 치즈', '외부 인기지표'],
      dtype='str')

In [3]:
df = df.sort_values(by='뷰어십', ascending=False)

df.to_csv('final_softcone_streamers_V2.csv', index=False, encoding='utf-8-sig')

In [7]:
import pandas as pd

df = pd.read_csv('fancafe_final.csv')

new_data = {
    'streamer_name': '징버거', 
    'cafe_id': 'woowakgood.com', 
    'fancafe_url': 'https://m.cafe.naver.com/steamindiegame.cafe', 
    'member_count': 573750, 
    'post_count': 15703221
}

new_df = pd.DataFrame([new_data])

df = pd.concat([df, new_df], ignore_index=True)

df.tail()

,streamer_name,cafe_id,fancafe_url,member_count,post_count
3466,김맞는,kimright0,https://cafe.naver.com/kimright0,151.0,2136.0
3467,꾸이링,guiling,https://cafe.naver.com/guiling,220.0,5403.0
3468,꿀 뭉,2,https://cafe.naver.com/f-e/cafes/31488341/arti...,17.0,107.0
3469,나다n가막,2,https://cafe.naver.com/nadangamak/2,17.0,107.0
3470,징버거,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0

In [8]:
new_data = {
    'streamer_name': '고세구', 
    'cafe_id': 'woowakgood.com', 
    'fancafe_url': 'https://m.cafe.naver.com/steamindiegame.cafe', 
    'member_count': 573750, 
    'post_count': 15703221
}

new_df = pd.DataFrame([new_data])

df = pd.concat([df, new_df], ignore_index=True)

df.tail()

,streamer_name,cafe_id,fancafe_url,member_count,post_count
3467,꾸이링,guiling,https://cafe.naver.com/guiling,220.0,5403.0
3468,꿀 뭉,2,https://cafe.naver.com/f-e/cafes/31488341/arti...,17.0,107.0
3469,나다n가막,2,https://cafe.naver.com/nadangamak/2,17.0,107.0
3470,징버거,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0
3471,고세구,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0

In [9]:
new_data = {
    'streamer_name': '주르르', 
    'cafe_id': 'woowakgood.com', 
    'fancafe_url': 'https://m.cafe.naver.com/steamindiegame.cafe', 
    'member_count': 573750, 
    'post_count': 15703221
}

new_df = pd.DataFrame([new_data])

df = pd.concat([df, new_df], ignore_index=True)

df.tail()

,streamer_name,cafe_id,fancafe_url,member_count,post_count
3468,꿀 뭉,2,https://cafe.naver.com/f-e/cafes/31488341/arti...,17.0,107.0
3469,나다n가막,2,https://cafe.naver.com/nadangamak/2,17.0,107.0
3470,징버거,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0
3471,고세구,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0
3472,주르르,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0

In [10]:
new_data = {
    'streamer_name': '비챤', 
    'cafe_id': 'woowakgood.com', 
    'fancafe_url': 'https://m.cafe.naver.com/steamindiegame.cafe', 
    'member_count': 573750, 
    'post_count': 15703221
}

new_df = pd.DataFrame([new_data])

df = pd.concat([df, new_df], ignore_index=True)

df.tail()

,streamer_name,cafe_id,fancafe_url,member_count,post_count
3469,나다n가막,2,https://cafe.naver.com/nadangamak/2,17.0,107.0
3470,징버거,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0
3471,고세구,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0
3472,주르르,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0
3473,비챤,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0

In [11]:
new_data = {
    'streamer_name': '릴파', 
    'cafe_id': 'woowakgood.com', 
    'fancafe_url': 'https://m.cafe.naver.com/steamindiegame.cafe', 
    'member_count': 573750, 
    'post_count': 15703221
}

new_df = pd.DataFrame([new_data])

df = pd.concat([df, new_df], ignore_index=True)

df.tail()

,streamer_name,cafe_id,fancafe_url,member_count,post_count
3470,징버거,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0
3471,고세구,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0
3472,주르르,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0
3473,비챤,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0
3474,릴파,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750.0,15703221.0

In [14]:
new_data = {
    'streamer_name': '아이네', 
    'cafe_id': 'woowakgood.com', 
    'fancafe_url': 'https://m.cafe.naver.com/steamindiegame.cafe', 
    'member_count': 573750, 
    'post_count': 15703221
}

new_df = pd.DataFrame([new_data])

df = pd.concat([df, new_df], ignore_index=True)

df.tail()

,streamer_name,cafe_id,fancafe_url,member_count,post_count
3472,주르르,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750,15703221
3473,비챤,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750,15703221
3474,릴파,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750,15703221
3475,아이네,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750,15703221
3476,아이네,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750,15703221

In [15]:

df = df.drop(3476)


df.tail()

,streamer_name,cafe_id,fancafe_url,member_count,post_count
3471,고세구,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750,15703221
3472,주르르,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750,15703221
3473,비챤,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750,15703221
3474,릴파,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750,15703221
3475,아이네,woowakgood.com,https://m.cafe.naver.com/steamindiegame.cafe,573750,15703221

In [16]:
# 컬럼 이름에 'count'가 포함된 애들만 찾아서 정수로 바꾸기!
for col in df.columns:
    if 'count' in col:
        df[col] = df[col].astype('Int64')
df.to_csv('fancafe_final.csv', index=False, encoding='utf-8-sig')

In [20]:
import pandas as pd
import re

# 선샌니의 3가지 규칙을 담은 마법의 전처리 함수!
def clean_streamer_name(name):
    # 만약 이름이 비어있다면(NaN) 그대로 패스!
    if pd.isna(name):
        return name
    
    name = str(name)
    
    # 규칙 1: 특수문자 무조건 제거 (한글, 영어, 숫자, 띄어쓰기만 남겨라!)
    name = re.sub(r'[^가-힣a-zA-Z0-9\s]', '', name)
    
    # 한글이 단 한 글자라도 포함되어 있는지 검사!
    if re.search(r'[가-힣]', name):
        # 규칙 2: 한글이 있으면 영문은 싹 지워버려라!
        name = re.sub(r'[a-zA-Z]', '', name)
    # 규칙 3: 한글이 없으면(영문만 있으면) 위 조건문을 안 타니까 영문 그대로 남음!
    
    # 마무리 단장: 너저분하게 남은 띄어쓰기들 깔끔하게 정리 (양끝 공백 싹둑!)
    name = re.sub(r'\s+', ' ', name).strip()
    
    return name

# 데이터 불러오기 (혹시 이미 df에 fancafe_final이 있다면 read_csv는 빼셔도 돼요!)
df_fancafe = pd.read_csv('fancafe_final.csv')

# 기존 'streamer_name' 열을 깨끗하게 씻겨서 다시 'streamer_name' 자리에 덮어쓰기! 드가자~
df_fancafe['streamer_name'] = df_fancafe['streamer_name'].apply(clean_streamer_name)

df_fancafe.to_csv('fancafe_final.csv', index=False, encoding='utf-8-sig')

In [5]:
import pandas as pd
import numpy as np

# 1. 데이터 불러오기
df = pd.read_csv('final_poongtoday_2385.csv')

# 2. '월별 방송 시간' 역산하기 (이건 아까랑 똑같아요!)
df['월별_방송시간'] = np.where(df['hourly_star'] > 0, df['total_star'] / df['hourly_star'], 0)

# 3. 🌟 여기가 핵심! 이름(name)과 아이디(channel_id)를 둘 다 써서 묶어줍니다!
# 이렇게 하면 아이디가 사라지지 않고 옆에 딱 붙어있게 돼요.
df_grouped = df.groupby(['name', 'channel_id']).agg(
    총_별풍선=('total_star', 'sum'),
    총_방송시간=('월별_방송시간', 'sum')
).reset_index()

# 4. 합산 데이터로 '시간당 별풍선' 다시 계산하기
df_grouped['시간당_별풍선_평균'] = np.where(
    df_grouped['총_방송시간'] > 0, 
    df_grouped['총_별풍선'] / df_grouped['총_방송시간'], 
    0
)

# 5. 정수형(Int64)으로 깔끔하게 정리하기
df_grouped['총_별풍선'] = df_grouped['총_별풍선'].astype('Int64')
df_grouped['시간당_별풍선_평균'] = df_grouped['시간당_별풍선_평균'].round().astype('Int64')

# 6. 중간 계산용 '총_방송시간'은 이제 안녕~
df_final = df_grouped.drop(columns=['총_방송시간'])

# 7. 1줄로 압축된 데이터를 새로운 파일로 저장! (나중에 합칠 때 이 파일을 쓰면 돼요!)
df_final.to_csv('final_poongtoday_2385.csv', index=False, encoding='utf-8-sig')

# 잘 압축됐는지, ID는 잘 살아있는지 확인!
df_final.head()

   name    channel_id    총_별풍선  시간당_별풍선_평균
0  #김미키  xxxkimmickey    98406          64
1  #레이#       ray7700        0           0
2   #미반    hobbyclass    12186           7
3  (설이)      mini8282  2196294         639
4   -지민    heewoo0310   111485          59

In [7]:
import pandas as pd
import numpy as np

# 1. 뼈대가 될 소프트콘 V2 데이터 불러오기
# (선샌니가 계속 덮어쓰기 하셨던 그 파일!)
df_softcone = pd.read_csv('final_softcone_streamers_V2.csv')

# 2. 1줄로 예쁘게 압축해둔 풍투데이 데이터 불러오기
# (아이디가 살아있는 최신 버전!)
df_poong = pd.read_csv('final_poongtoday_2385.csv')

# 3. 대공사 시작! channel_id를 기준으로 합치기 (LEFT JOIN)
# 소프트콘 목록은 그대로 유지하고, 풍투데이에서 [channel_id, 총_별풍선, 시간당_별풍선_평균]만 빌려옵니다.
df_merged = pd.merge(
    df_softcone, 
    df_poong[['channel_id', '총_별풍선', '시간당_별풍선_평균']], 
    on='channel_id', 
    how='left'
)

# 4. 빌려온 값들을 우리가 미리 만들어둔 '빈칸' 컬럼에 쏙쏙 이사시키기
df_merged['별풍선 도네이션'] = df_merged['총_별풍선']
df_merged['시간당 별풍선'] = df_merged['시간당_별풍선_평균']

# 5. 이사가 끝났으니 임시로 썼던 기둥('총_별풍선', '시간당_별풍선_평균')은 철거!
df_merged.drop(columns=['총_별풍선', '시간당_별풍선_평균'], inplace=True)

# 6. 마무리 청소: 소수점 떼고 깔끔하게 정수(Int64)로 변환
df_merged['별풍선 도네이션'] = df_merged['별풍선 도네이션'].astype('Int64')
df_merged['시간당 별풍선'] = df_merged['시간당 별풍선'].astype('Int64')

# 7. 완성된 데이터를 다시 V2에 덮어쓰기! 쾅쾅!
df_merged.to_csv('final_softcone_streamers_V2.csv', index=False, encoding='utf-8-sig')

# 결과가 얼마나 예쁜지 상위 5명만 스윽 볼까요?
df_merged[['streamer_name', 'channel_id', '별풍선 도네이션', '시간당 별풍선']].head()

  streamer_name                        channel_id  별풍선 도네이션  시간당 별풍선
0          탬탬버린  a7e175625fdea5a7d98428302b7aa57f      <NA>     <NA>
1        텐코 시부키  64d76089fba26b180d9c9e48a32600d9      <NA>     <NA>
2           아리사  4de764d9dad3b25602284be6db3ac647      <NA>     <NA>
3       아라하시 타비  a6c4ddb09cdb160478996007bff35296      <NA>     <NA>
4           고세구                           gosegu2   5905590     3853