# 숙제 시작

## 5번째 세그먼트 중고신입형

**작업계( 그림, 코스프레 등) 으로 인기( 트래픽, 팔로워)를 확보해 두었지만 버츄얼 규모는 작거나 신규인 스트리머**

예시 분석용 핵심 KPI : X_팔로워, 팬카페_가입자, 유튜브_구독자, 팬덤지수, 최고_팔로워

다시 정의 : 외부 커뮤니티(SNS, 유튜브 등)의 체급은 상위권이지만, 생방송(버추얼) 지표는 하위권~중위권인 스트리머

#### 조건1 : 플랫폼 이외의 외부 지표가 유의미한 영향력을 가졌는지 절대 수치로 검증

트위터, 유튜브, 팬카페 중 하나라도 두각을 보여야 함

- KPI 세팅: X_팔로워, 팬카페_가입자, 유튜브_구독자 중 하나라도 TOP 100


#### 조건2 : 버츄얼 체급은 아직 신입일 것

본업(버츄얼 이전 직업) 위주로 활동해서 아직 생방송 고정 시청자가 크지 않아야 함 

이전에 만들었던 유튜브_유입지수와 팬덤지수
- 분모 : 팔로워 
- 분자 : 외부 지표 (유튜브_구독자, 팬카페_가입자, X_팔로워)

-> 현재 플랫폼 체급이 작을수록 지수값이 커짐

-> 유튜브나 SNS 화력이 셀수록 지수값이 커짐

- 지수가 높다는 것 자체가 "본업(작업계) 인기에 비해 아직 방송 규모가 작다"는 것을 산술적으로 증명


- 유튜브_유입지수, 팬덤지수 중 하나라도 TOP 100

---

##### 조건1(외부 커뮤니티 체급 상위권)과 조건2(버츄얼 체급은 신입)를 동시에 만족하는 경우 

##### -> '중고신입형' 세그먼트로 분류

----

조건 1 : 상위 10%의 SNS지수 보기

In [5]:
import pandas as pd

df = pd.read_csv('final_softcone.csv')

cols = ['X_팔로워', '팬카페_가입자', '유튜브_구독자']
for col in cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

top10_cut = df[cols].quantile(0.9)

print("상위 10% 컷")
display(top10_cut)

상위 10% 컷

X_팔로워       426.4
팬카페_가입자     216.0
유튜브_구독자    3014.0
Name: 0.9, dtype: float64

In [10]:
df['X_팔로워'].describe()

count     11157.000000
mean        488.257238
std        6185.575552
min           0.000000
25%           0.000000
50%           0.000000
75%           6.000000
max      351000.000000
Name: X_팔로워, dtype: float64

하위 50% 가 모두 0이라서 상위 10%가 낮게 나옴

팔로워가 0인 사람들을 제외하고 거기서 보자

In [15]:
import pandas as pd
import numpy as np

# 1. 데이터 로드
df = pd.read_csv('final_softcone.csv')

def get_active_thresholds(df, column, percentiles):
    """
    특정 컬럼에서 0을 제외한 데이터만을 대상으로 상위 N% 임계값을 계산 
    """
    active_data = df[df[column] > 0][column]
    
    if active_data.empty:
        return [0] * len(percentiles)
    
    # 상위 N% 계산 후 반올림하여 정수로 변환
    results = active_data.quantile([1 - (p/100) for p in percentiles])
    return results.round().astype(int).values

# 2. 분석 설정
target_cols = ['유튜브_구독자', '팬카페_가입자', 'X_팔로워']
percents = [5, 10, 15]

# 3. 결과 계산 및 출력
print(f"{'지표':<15} | {'활동자 수':<8} | {'상위 5%':<10} | {'상위 10%':<10} | {'상위 15%':<10}")
print("-" * 70)

for col in target_cols:
    active_count = len(df[df[col] > 0])
    v5, v10, v15 = get_active_thresholds(df, col, percents)
    
    # :d 또는 :,d 를 사용하면 정수형으로 콤마까지 찍어서 출력 가능해
    print(f"{col:<15} | {active_count:<10,d} | {v5:<12,d} | {v10:<12,d} | {v15:<12,d}")

# 4. 변수 저장용 (나중에 필터링 조건으로 쓸 때)
yt_10 = int(df[df['유튜브_구독자'] > 0]['유튜브_구독자'].quantile(0.90))
cafe_10 = int(df[df['팬카페_가입자'] > 0]['팬카페_가입자'].quantile(0.90))
x_10 = int(df[df['X_팔로워'] > 0]['X_팔로워'].quantile(0.90))

print(f"\n상위 10%:")
print(f"유튜브: {yt_10:,}명 | 팬카페: {cafe_10:,}명 | X: {x_10:,}명")

지표              | 활동자 수    | 상위 5%      | 상위 10%     | 상위 15%
----------------------------------------------------------------------
유튜브_구독자         | 6,880      | 21,615       | 7,215        | 3,420
팬카페_가입자         | 5,338      | 2,884        | 834          | 373
X_팔로워           | 2,877      | 4,063        | 1,710        | 1,142

상위 10%:
유튜브: 7,215명 | 팬카페: 834명 | X: 1,709명

### 생각보다 낮음 + 활동자 수가 달라서 뽑히는 사람 수가 다름

-> **TOP 100** 으로 뽑자

In [24]:
import pandas as pd


# X(트위터) 상위 100명
x_top100 = df[df['X_팔로워'] > 0].nlargest(100, 'X_팔로워')[['스트리머명', 'X_팔로워']]

# 유튜브 상위 100명
yt_top100 = df[df['유튜브_구독자'] > 0].nlargest(100, '유튜브_구독자')[['스트리머명', '유튜브_구독자']]

# 팬카페 상위 100명
cafe_top100 = df[df['팬카페_가입자'] > 0].nlargest(100, '팬카페_가입자')[['스트리머명', '팬카페_가입자']]

# 3. 조건 1의 통합 후보군 생성 (중복 제거)
# 세 그룹 중 하나라도 속하면 '외부 팬덤 확실'군으로 분류
condition_1_candidates = pd.concat([x_top100['스트리머명'], yt_top100['스트리머명'], cafe_top100['스트리머명']]).unique()

print(f"조건 1 통합 후보군 수: {len(condition_1_candidates)}명")

조건 1 통합 후보군 수: 225명

In [25]:
x_top100

              스트리머명   X_팔로워
3894           릴리작가  351000
6585            리코링  252000
4711           오투 2  184000
342              포냐  150000
5715  DIO fevercell  121000
...             ...     ...
552             미시코    6874
3891            쇼 카    6792
839             이레인    6762
1313            김맞는    6761
87           블레어 로즈    6757

[100 rows x 2 columns]

In [26]:
yt_top100

        스트리머명  유튜브_구독자
175      하우카우  2210000
863       쁘 허  1090000
61        램램1  1040000
566       대월향  1000000
136        늦잠   900000
...       ...      ...
839       이레인   124000
5077  즐기는 남자들   120000
39      조디악악악   119000
131      감제이님   119000
2085       디움   118000

[100 rows x 2 columns]

In [27]:
cafe_top100

       스트리머명  팬카페_가입자
4        고세구   573411
7         릴파   573411
13        비챤   573411
15       아이네   573411
18       징버거   573411
...      ...      ...
96      뢴트게늄    14670
14    달콤레나 씨    14620
150      이오몽    14376
449       유콘    14243
2085      디움    13816

[100 rows x 2 columns]

### TOP 100 컷

- X : 6757

- 유튜브 : 118000

- 팬카페 : 13816

- 합쳐서 219명

# 데이터 뽑기

In [6]:
import pandas as pd

# 1. 데이터 불러오기 (파일명은 실제 파일명으로 수정해주세요)
df = pd.read_csv('final_softcone.csv')

# =====================================================================
# [조건 1] 외부 커뮤니티 체급 상위권 (절대 수치 TOP 100)
# =====================================================================
# 각 지표별 상위 100명의 인덱스 추출 (0인 데이터는 제외)
top100_x = df[df['X_팔로워'] > 0].nlargest(200, 'X_팔로워').index
top100_yt = df[df['유튜브_구독자'] > 0].nlargest(200, '유튜브_구독자').index
top100_cafe = df[df['팬카페_가입자'] > 0].nlargest(200, '팬카페_가입자').index

# 세 지표 중 하나라도 TOP 100에 속하는 인원 (합집합)
cond1_idx = top100_x.union(top100_yt).union(top100_cafe)
cond1_mask = df.index.isin(cond1_idx)

# =====================================================================
# [조건 2] 버츄얼 체급은 아직 신입일 것 (상한선 + 지수 TOP 100)
# =====================================================================
# 2-1. 상한선(Upper Limit) 설정: 플랫폼 팔로워가 전체 평균 이하일 것
#mean_followers = df['최고_팔로워'].mean()
#upper_bound_mask = df['최고_팔로워'] <= mean_followers

# 2-2. 지표 비율 기준 TOP 100 추출
top100_yt_index = df.nlargest(100, '유튜브_유입지수').index
top100_fandom_index = df.nlargest(100, '팬덤지수').index

# 두 지수 중 하나라도 TOP 100에 속하는 인원
cond2_idx = top100_yt_index.union(top100_fandom_index)
index_mask = df.index.isin(cond2_idx)

# 조건 2 최종 마스크 (평균 이하의 팔로워 AND 지수 TOP 100)
cond2_mask = index_mask

# =====================================================================
# [최종 추출] 세그먼트 5: 중고신입형
# =====================================================================
# 조건 1과 조건 2를 동시에 만족하는 교집합 데이터 추출
segment_5_df = df[cond1_mask & cond2_mask]

# =====================================================================
# 결과 확인 및 저장
# =====================================================================
print(f"[데이터 요약]")
print(f"1. 조건 1(외부 네임드) 통과자: {cond1_mask.sum()}명")
print(f"2. 조건 2(방송 신입 + 지수 상위) 통과자: {cond2_mask.sum()}명")
print("-" * 40)
print(f"최종 세그먼트 5 (중고신입형) 발굴 인원: {len(segment_5_df)}명")

# 추출된 데이터를 CSV 파일로 저장 (팀원 공유용, 한글 깨짐 방지 utf-8-sig)
segment_5_df.to_csv('segment5_used_newbie.csv', index=False, encoding='utf-8-sig')

# 결과 데이터프레임 미리보기 (상위 5명)
segment_5_df[['스트리머명', '최고_팔로워', 'X_팔로워', '유튜브_구독자', '팬카페_가입자', '유튜브_유입지수', '팬덤지수']].head(60)

[데이터 요약]
1. 조건 1(외부 네임드) 통과자: 428명
2. 조건 2(방송 신입 + 지수 상위) 통과자: 187명
----------------------------------------
최종 세그먼트 5 (중고신입형) 발굴 인원: 24명

               스트리머명  최고_팔로워   X_팔로워  유튜브_구독자  팬카페_가입자  유튜브_유입지수   팬덤지수
2403             태비군     293       0    56900       34      92.6  -35.1
3608            나는코히     180       0    62000        0     112.3 -100.0
3810             라오당     160    3535       19        0     -41.0   60.8
3894            릴리작가    1916  351000      801       74     -11.5   68.9
4711            오투 2    2492  184000        0        0    -100.0   55.0
5172            몬드몬드     399   10000       16     1405     -52.7   56.2
5349            작은의자     288   12000        0        1    -100.0   65.8
5715   DIO fevercell     439  121000     3850        0      35.6   92.3
5760         아니지 000     460   31260     2230        0      25.7   68.8
6092            미으낙서     233   13956        0        0    -100.0   74.9
6140             하마쟝     201    7711       13        0     -50.3   68.6
6464            비하와와     116    4502       49        0     -17.9   76.7
6585             리코링     638  252000        0        0    -100.0   92.5
7037             이천일     341       0    74700        0      92.3 -100.0
7055              시신     677  119000     3300      235      24.3   79.3
7161            총며칠ㅡ     237       0    91700        0     108.8 -100.0
7369             키테라    1237   89000     3150        0      13.1   60.0
8039         츠키요미 미호     143   11000        0        0    -100.0   87.2
8073              냥찬      70   19669       10        0     -43.7  131.9
8690            치로미2     185   25398        0        0    -100.0   94.1
8961              수콩     146   18088        0        0    -100.0   96.4
9999            리아 뇌      43    2878     2210        0     103.5  110.5
10712            앤무디      11    3278        0       16    -100.0  226.0
10895          xesii      23    8060     1800        0     135.9  183.0

In [4]:
import pandas as pd

# 1. 데이터 불러오기 (파일명은 실제 파일명으로 수정해주세요)
df = pd.read_csv('final_softcone.csv')

# =====================================================================
# [조건 1] 외부 커뮤니티 체급 상위권 (절대 수치 TOP 100)
# =====================================================================
# 각 지표별 상위 100명의 인덱스 추출 (0인 데이터는 제외)
top100_x = df[df['X_팔로워'] > 0].nlargest(100, 'X_팔로워').index
top100_yt = df[df['유튜브_구독자'] > 0].nlargest(100, '유튜브_구독자').index
top100_cafe = df[df['팬카페_가입자'] > 0].nlargest(100, '팬카페_가입자').index

# 세 지표 중 하나라도 TOP 100에 속하는 인원 (합집합)
cond1_idx = top100_x.union(top100_yt).union(top100_cafe)
cond1_mask = df.index.isin(cond1_idx)

# =====================================================================
# [조건 2] 버츄얼 체급은 아직 신입일 것 (상한선 + 지수 TOP 100)
# =====================================================================
# 2-1. 상한선(Upper Limit) 설정: 플랫폼 팔로워가 전체 평균 이하일 것
#mean_followers = df[df['최고_팔로워'] > 0]['최고_팔로워'].mean()
#upper_bound_mask = df['최고_팔로워'] <= mean_followers

# 2-2. 지표 비율 기준 TOP 100 추출
top100_yt_index = df.nlargest(100, '유튜브_유입지수').index
top100_fandom_index = df.nlargest(100, '팬덤지수').index

# 두 지수 중 하나라도 TOP 100에 속하는 인원
cond2_idx = top100_yt_index.union(top100_fandom_index)
index_mask = df.index.isin(cond2_idx)

# 조건 2 최종 마스크 (평균 이하의 팔로워 AND 지수 TOP 100)
cond2_mask = index_mask

# =====================================================================
# [최종 추출] 세그먼트 5: 중고신입형
# =====================================================================
# 조건 1과 조건 2를 동시에 만족하는 교집합 데이터 추출
segment_5_df = df[cond1_mask & cond2_mask]

# =====================================================================
# 결과 확인 및 저장
# =====================================================================
print(f"[데이터 요약]")
print(f"1. 조건 1(외부 네임드) 통과자: {cond1_mask.sum()}명")
print(f"2. 조건 2(방송 신입 + 지수 상위) 통과자: {cond2_mask.sum()}명")
print("-" * 40)
print(f"최종 세그먼트 5 (중고신입형) 발굴 인원: {len(segment_5_df)}명")

# 추출된 데이터를 CSV 파일로 저장 (팀원 공유용, 한글 깨짐 방지 utf-8-sig)
segment_5_df.to_csv('segment5_used_newbie.csv', index=False, encoding='utf-8-sig')

# 결과 데이터프레임 미리보기 (상위 5명)
segment_5_df[['스트리머명', '최고_팔로워', 'X_팔로워', '유튜브_구독자', '팬카페_가입자', '유튜브_유입지수', '팬덤지수']].head(16)

[데이터 요약]
1. 조건 1(외부 네임드) 통과자: 219명
2. 조건 2(방송 신입 + 지수 상위) 통과자: 187명
----------------------------------------
최종 세그먼트 5 (중고신입형) 발굴 인원: 16명

               스트리머명  최고_팔로워   X_팔로워  유튜브_구독자  팬카페_가입자  유튜브_유입지수   팬덤지수
3894            릴리작가    1916  351000      801       74     -11.5   68.9
4711            오투 2    2492  184000        0        0    -100.0   55.0
5172            몬드몬드     399   10000       16     1405     -52.7   56.2
5349            작은의자     288   12000        0        1    -100.0   65.8
5715   DIO fevercell     439  121000     3850        0      35.6   92.3
5760         아니지 000     460   31260     2230        0      25.7   68.8
6092            미으낙서     233   13956        0        0    -100.0   74.9
6140             하마쟝     201    7711       13        0     -50.3   68.6
6585             리코링     638  252000        0        0    -100.0   92.5
7055              시신     677  119000     3300      235      24.3   79.3
7369             키테라    1237   89000     3150        0      13.1   60.0
8039         츠키요미 미호     143   11000        0        0    -100.0   87.2
8073              냥찬      70   19669       10        0     -43.7  131.9
8690            치로미2     185   25398        0        0    -100.0   94.1
8961              수콩     146   18088        0        0    -100.0   96.4
10895          xesii      23    8060     1800        0     135.9  183.0

In [50]:
import pandas as pd

# 파일 불러오기
df = pd.read_csv('final_softcone.csv')

# 숫자형 변환 (안전하게)
df['유튜브_유입지수'] = pd.to_numeric(df['유튜브_유입지수'], errors='coerce')

# 내림차순 정렬
df_sorted = df.sort_values(by='유튜브_유입지수', ascending=False)

# 상위 20개 보기
df_sorted.head(20)

,스트리머명,플랫폼,채널ID,집계기간_내_최초_방송일,최고_팔로워,총_방송시간,6분_최고채팅,6분_평균채팅_최댓값,최고_시청자,평균_시청자_최댓값,뷰어십,도네이션,유튜브_유입지수,팬덤지수,X_팔로워,유튜브_구독자,팬카페_가입자,팬카페_그룹여부
11084,라이 알카라인,CHZZK,578f711570aaf315c76ebca9d47ae90b,2026.03.30 ~ 2026.03.30,1,1,10,3,1,1,1,0,816.0,-100.0,0,571,0,NaN
10180,미라클 제이,SOOP,miraclej,2025.02.25 ~ 2026.03.21,2,120,48,7,4,3,135,0,652.2,56.8,0,3880,4,NaN
11146,세타,SOOP,seta0901,2026.03.17 ~ 2026.03.17,1,0,0,0,1,1,0,0,517.0,250.5,0,71,9,False
11044,심크크,CHZZK,b3bc23f39d24a2e9c4cd87f0d82defd9,2025.12.15 ~ 2026.03.30,1,4,2,0,3,2,3,0,510.9,198.2,0,68,6,False
9815,기록노예티로,SOOP,dovahkiin294,2025.05.26 ~ 2026.03.31,6,145,4,0,5,4,233,0,427.7,-100.0,0,28800,0,NaN
11152,sophiaten,SOOP,sophiaten,2026.03.20 ~ 2026.03.20,5,1,0,0,2,0,0,0,361.5,-100.0,0,3900,0,NaN
10674,Alteria,SOOP,alteria,2026.02.05 ~ 2026.03.13,5,10,8,2,8,5,42,264,342.8,-100.0,0,2790,0,NaN
9202,고라,SOOP,duddnjs2450,2025.09.25 ~ 2026.03.31,9,141,11,1,8,5,446,250,306.1,-100.0,0,11500,0,NaN
9843,KuraseTaoh,SOOP,oatsukaresan,2026.02.20 ~ 2026.03.31,11,54,8,1,8,6,223,418,292.2,-100.0,0,17100,0,NaN
9642,수,SOOP,sookun92,2025.02.10 ~ 2026.03.29,6,247,5,0,4,3,290,0,290.1,-100.0,0,1980,0,NaN
11149,잔파도,CHZZK,c14f2e20e8584643cb99ff2cea4e132b,2026.03.14 ~ 2026.03.15,2,0,7,6,4,3,0,0,271.2,437.3,365,58,0,NaN
10607,에트에트,CHZZK,6fce81485e1a034fa0ee49750d16c3f6,2025.07.06 ~ 2026.03.04,6,76,30,7,4,1,52,0,269.7,-100.0,0,1330,0,NaN
11035,지갱만족센터,CHZZK,88eb206a0327358852e20c621804a8a9,2026.03.24 ~ 2026.03.29,2,5,12,7,4,2,4,0,264.8,-100.0,0,54,0,NaN
10887,화니,CHZZK,21c2713c0005dbd9c5f6495312af5835,2026.03.19 ~ 2026.03.20,3,9,23,4,5,2,14,0,238.4,100.0,15,108,0,NaN
10875,플루,CHZZK,5c1be352b4c8c78b253cba3cdb6a2d44,2026.03.21 ~ 2026.03.29,8,6,13,2,9,3,15,0,233.8,-100.0,0,1530,0,NaN
10547,래작이임다,SOOP,kctugygcey,2025.01.12 ~ 2026.03.15,4,78,28,9,4,3,65,0,231.0,-100.0,0,205,0,NaN
9581,mokiminavt,SOOP,mokiminavt,2026.01.31 ~ 2026.03.10,16,70,14,5,11,7,308,370,226.1,-100.0,0,10300,0,NaN
10512,채멀,SOOP,chatmurtalk,2026.03.04 ~ 2026.03.26,20,15,11,1,8,6,70,339,223.9,-100.0,0,19200,0,NaN
8784,埃莉絲,SOOP,vtubereirlys,2026.02.06 ~ 2026.03.28,8,100,6,0,23,13,608,100,213.6,-100.0,0,981,0,NaN
9497,은비,SOOP,yinfei,2026.03.01 ~ 2026.03.30,17,49,10,3,41,33,336,293,208.9,-100.0,0,7550,0,NaN

# 20230506 다시 해보기

조건2에서 팬심지수는 X팔로워랑 카페회원수를 같이봄


팬심지수(X&팬카페)에서 -> X 유입지수

$$ X\text{ 유입지수} = \frac{\log_{10}(X\_\text{팔로워} + 1)}{\log_{10}(\text{최고\_팔로워} + 1)} $$

In [48]:
import pandas as pd
import numpy as np

# 1. 데이터 불러오기
df = pd.read_csv('final_softcone.csv')


# X_유입지수 생성 (분모 0 처리를 위해 log10 적용 시 +1)
df['X_유입지수'] = np.log10(df['X_팔로워'] + 1) / np.log10(df['최고_팔로워'] + 1)

# inf(무한대)를 0으로 치환 (최고_팔로워가 0인 경우 대비)
df['X_유입지수'] = df['X_유입지수'].replace([np.inf, -np.inf], np.nan).fillna(0)

# =====================================================================
# [조건 1] 외부 커뮤니티 체급 상위권 (절대 수치 TOP 100)
# =====================================================================
top100_x = df[df['X_팔로워'] > 0].nlargest(200, 'X_팔로워').index
top100_yt = df[df['유튜브_구독자'] > 0].nlargest(200, '유튜브_구독자').index

cond1_idx = top100_x.union(top100_yt)
cond1_mask = df.index.isin(cond1_idx)

# =====================================================================
# [조건 2] 버츄얼 체급은 아직 신입일 것 (상한선 + 지수 TOP 100)
# =====================================================================

#mean_followers = df[df['최고_팔로워'] > 0]['최고_팔로워'].mean()
#upper_bound_mask = df['최고_팔로워'] <= mean_followers

# 2-2. 지표 비율 기준 TOP 100 추출 (유튜브와 X의 유입지수 활용)
top100_yt_inflow = df.nlargest(200, '유튜브_유입지수').index
top100_x_inflow = df.nlargest(200, 'X_유입지수').index

cond2_idx = top100_yt_inflow.union(top100_x_inflow)
index_mask = df.index.isin(cond2_idx)

# 최종 조건 2: 지수 상위권이면서 + 동시에 방송 체급은 평균 이하일 것
cond2_mask = index_mask 


# [최종 추출] 세그먼트 5: 중고신입형

segment_5_df = df[cond1_mask & cond2_mask]


# 결과 확인 
print(f"[데이터 요약]")
print(f"1. 조건 1(외부 네임드) 통과자: {cond1_mask.sum()}명")
print(f"2. 조건 2(지수 상위 & 신입 체급) 통과자: {cond2_mask.sum()}명")
print("-" * 40)
print(f"최종 세그먼트 5 (중고신입형) 발굴 인원: {len(segment_5_df)}명")

# CSV 저장
#segment_5_df.to_csv('segment5_used_newbie_v2.csv', index=False, encoding='utf-8-sig')

display_cols = ['스트리머명', '최고_팔로워', 'X_팔로워', '유튜브_구독자', '유튜브_유입지수', 'X_유입지수']
(segment_5_df[display_cols].sort_values(by='X_유입지수', ascending=False).tail(50))

[데이터 요약]
1. 조건 1(외부 네임드) 통과자: 353명
2. 조건 2(지수 상위 & 신입 체급) 통과자: 378명
----------------------------------------
최종 세그먼트 5 (중고신입형) 발굴 인원: 69명

         스트리머명  최고_팔로워   X_팔로워  유튜브_구독자  유튜브_유입지수    X_유입지수
5172      몬드몬드     399   10000       16     -52.7  1.537260
5240        냥족     596   15602        0    -100.0  1.510536
7481     YUDOK     254    4204       83     -20.0  1.505799
4671        그잉     680   16000    23600      54.3  1.483914
6466  DODOYUKI     295    4294      259      -2.3  1.470067
1765      천수천수     759   17000        0    -100.0  1.468500
5824       히이인     215    2634       11     -53.8  1.465345
8549       아연화     470    7423     3180      31.0  1.448039
6358        모브     512    8253        0    -100.0  1.445201
2793        프록     763   14000        8     -66.9  1.438094
4963        후카     443    6280      488       1.6  1.434635
8762   조장하겠습니다     401    5189     1900      25.9  1.426592
4250      누운누운     336    3971       76     -25.4  1.423867
8338       오월님     377    4621     1910      27.3  1.421859
2302   웃상 작업계정    2178   53000     5540      12.1  1.415195
3389       쵸 쵸     855   14000       81     -34.7  1.413878
5587     브이레코드     490    5617    14000      54.1  1.393336
2933      소보로시     352    3535       58     -30.5  1.392789
1975      다로로다    2016   33000     1940      -0.5  1.367301
1213        릴루    4219   87200     1150     -15.6  1.362785
2077     마신멜로우    1164   15000     9770      30.1  1.361930
6733      어퍼캐럿     361    2939       58     -30.8  1.355507
5392       오로지     622    5898      137     -23.4  1.349363
2246       영도씨     575    5089       42     -40.8  1.342808
4983      차이니아     563    4745      269     -11.6  1.336225
3067  모모무네 앨리스     880    8467      207     -21.3  1.333723
4714      하나비양    1324   13403    28600      42.7  1.321893
801        웨히히    1772   18800      494     -17.1  1.315655
3057      한라감귤    4618   61000     4070      -1.5  1.305846
7940        샨곰     774    5594   112000      74.8  1.297130
342         포냐   10091  150000     2480     -15.2  1.292738
2296       김염록    1385    9314     6380      21.1  1.263362
256       서랑그림   11210  116000    19300       5.8  1.250594
4032   하나토리 아논     707    3400     1740      13.7  1.239146
6597       참빼미     918    4518    13000      38.8  1.233430
1158      수이수이    4081   28000    13700      14.6  1.231606
6921       깅도이    2123    1400   257000      62.6  0.945684
8166        헤키    1083      74    77100      61.0  0.617807
2403       태비군     293       0    56900      92.6  0.000000
1522       기막사    1718       0   104000      55.1  0.000000
2612       피큐큐    1391       0   180000      67.2  0.000000
3608      나는코히     180       0    62000     112.3  0.000000
4581        우현     477       0    51700      75.9  0.000000
4443       세모미    1468       0    88000      56.1  0.000000
4502   로블록스 완뚜    1032       0    48700      55.5  0.000000
6213        진찡    1936       0   133000      55.9  0.000000
7161      총며칠ㅡ     237       0    91700     108.8  0.000000
7037       이천일     341       0    74700      92.3  0.000000
8954    나는 범이요     679       0   101000      76.7  0.000000
8855       워니이     499       0    58200      76.5  0.000000

### 유튜브 유입지수, X_유입지수 기준

In [45]:

yt_inflow_cut = df.nlargest(200, '유튜브_유입지수')['유튜브_유입지수'].min()

# 2. X 유입지수 TOP 100의 최솟값 (100위의 점수)
x_inflow_cut = df.nlargest(200, 'X_유입지수')['X_유입지수'].min()

print(f"[지수 커트라인 확인]")
print(f"1. 유튜브 유입지수 TOP 100 컷: {yt_inflow_cut:.4f}")
print(f"2. X_유입지수 TOP 100 컷: {x_inflow_cut:.4f}")
print("-" * 40)

if len(segment_5_df) > 0:
    print(f"최종 27명의 지수 분포")
    print(f"- 유튜브 유입지수 범위: {segment_5_df['유튜브_유입지수'].min():.2f} ~ {segment_5_df['유튜브_유입지수'].max():.2f}")
    print(f"- X_유입지수 범위: {segment_5_df['X_유입지수'].min():.2f} ~ {segment_5_df['X_유입지수'].max():.2f}")
else:
    print("검색된 인원이 없습니다. 로직을 다시 확인해주세요.")

[지수 커트라인 확인]
1. 유튜브 유입지수 TOP 100 컷: 54.2000
2. X_유입지수 TOP 100 컷: 1.2233
----------------------------------------
최종 27명의 지수 분포
- 유튜브 유입지수 범위: -100.00 ~ 135.90
- X_유입지수 범위: 0.00 ~ 3.26

### 유튜브 팔로워, X 팔로워 기준

In [52]:

# 1. 유튜브 구독자
yt_subs_cut = df[df['유튜브_구독자'] > 0].nlargest(200, '유튜브_구독자')['유튜브_구독자'].min()

# 2. X(트위터) 팔로워 
x_fol_cut = df[df['X_팔로워'] > 0].nlargest(200, 'X_팔로워')['X_팔로워'].min()

print(f"[조건 1: 외부 영향력 커트라인]")
print(f"1. 유튜브 구독자 TOP 100 컷: {yt_subs_cut:,}명")
print(f"2. X(트위터) 팔로워 TOP 100 컷: {x_fol_cut:,}명")
print("-" * 40)

# 4. 최종 27명의 실제 외부 체급 평균 확인
if len(segment_5_df) > 0:
    print(f"최종 발굴된 27명의 평균 체급")
    print(f"- 평균 유튜브 구독자: {segment_5_df['유튜브_구독자'].mean():,.0f}명")
    print(f"- 평균 X 팔로워: {segment_5_df['X_팔로워'].mean():,.0f}명")
    print(f"- 평균 최고 팔로워(방송): {segment_5_df['최고_팔로워'].mean():,.0f}명")

[조건 1: 외부 영향력 커트라인]
1. 유튜브 구독자 TOP 100 컷: 47,800명
2. X(트위터) 팔로워 TOP 100 컷: 2,634명
----------------------------------------
최종 발굴된 27명의 평균 체급
- 평균 유튜브 구독자: 24,174명
- 평균 X 팔로워: 29,664명
- 평균 최고 팔로워(방송): 1,168명

In [26]:
import numpy as np
df_aa = pd.read_csv('final_softcone.csv')
# 1. 지수 계산
df_aa['X_유입지수'] = np.log10(df_aa['X_팔로워'] + 1) / np.log10(df_aa['최고_팔로워'] + 1)

# 2. inf(무한대)를 NaN(결측치)으로 바꾼 뒤, 모든 NaN을 0으로 채우기
df_aa['X_유입지수'] = df_aa['X_유입지수'].replace([np.inf, -np.inf], np.nan).fillna(0)
# 3. 결과 다시 확인
top_50_x_index = df_aa.nlargest(50, 'X_유입지수')
print("X_유입지수 상위 50명 명단")
(top_50_x_index[['스트리머명', 'X_유입지수', 'X_팔로워', '최고_팔로워']].head(50))

X_유입지수 상위 50명 명단

               스트리머명    X_유입지수   X_팔로워  최고_팔로워
11149            잔파도  5.372808     365       2
10972     크라운 크라우페이퍼  4.394921     124       2
10996           아귀찌무  3.680144      56       2
10712            앤무디  3.257786    3278      11
10895          xesii  2.830283    8060      23
11057            필레몬  2.763340     312       7
10984           아쿠바스  2.516992     133       6
10770           나대로롱  2.322345      41       4
8073              냥찬  2.319398   19669      70
9999            리아 뇌  2.104862    2878      43
10887             화니  2.000000      15       3
11124            파 벨  1.966679     361      19
8961              수콩  1.964371   18088     146
8690            치로미2  1.940864   25398     185
6585             리코링  1.925290  252000     638
5715   DIO fevercell  1.922784  121000     439
10845         루루 입니당  1.912773     471      24
10711            천랑ㄱ  1.912514    1271      41
10923      다기네 그림 공방  1.897970     718      31
8039         츠키요미 미호  1.872453   11000     143
10596           하리은우  1.869391     473      26
10116             르렌  1.845418     228      18
10901      호야 ㅣ 적패호관  1.837685     317      22
10697            이로포  1.798489     567      33
7055              시신  1.792702  119000     677
6464            비하와와  1.766525    4502     116
11099           네이 모  1.753493      66      10
6092            미으낙서  1.749436   13956     233
9797             TAS  1.743645     704      42
9190          류월0317  1.734469    1431      65
10422             쪼리  1.730409     643      41
10994        그라나1127  1.703930      68      11
9563              글루  1.703320     949      55
9478             민숭이  1.696763     357      31
10803             라센  1.694536     133      17
3894            릴리작가  1.689292  351000    1916
5760         아니지 000  1.687503   31260     460
6140             하마쟝  1.686149    7711     201
10509            누아루  1.668754     341      32
5349            작은의자  1.657613   12000     288
10961            손겨울  1.638612     113      17
3810             라오당  1.607971    3535     160
8350            검은망치  1.607886     249      30
7369             키테라  1.600337   89000    1237
9351          천청 001  1.597981     453      45
10853            이용자  1.584963      80      15
10151          리에곤듀님  1.565532     843      73
10069            시카모  1.552866     166      26
9987           행복한냠쿤  1.551212     695      67
4711            오투 2  1.549971  184000    2492